# Feature Engineering
Criacao de features e preparacao dos dados para etapa de Machine Learning

#### Imports

In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from unidecode import unidecode

pd.set_option('display.max_columns', None)

## Load data

In [2]:
PATH = '../data/processed/'

### Dados das Escolas (SARESP)

In [3]:
df_escolas = pd.read_csv(os.path.join(PATH, 'escolas_saresp_2018.csv'), sep=',')
print(df_escolas.shape)
df_escolas.head()

(20378, 14)

,DEPADM,DepBol,NomeDepBol,codRMet,CODESC,NOMESC,SERIE_ANO,cod_per,periodo,co_comp,ds_comp,medprof,PONTUACAO,DESEMPENHO
0,1,1,Rede Estadual,1,12,AYRES DE MOURA PROFESSOR,9º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,263.1,BASICO,RUIM
1,1,1,Rede Estadual,1,12,AYRES DE MOURA PROFESSOR,9º Ano EF,9,GERAL,2,MATEMÁTICA,272.3,BASICO,RUIM
2,1,1,Rede Estadual,1,24,GAVIAO PEIXOTO BRIGADEIRO,3º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,170.4,BASICO,RUIM
3,1,1,Rede Estadual,1,24,GAVIAO PEIXOTO BRIGADEIRO,3º Ano EF,9,GERAL,2,MATEMÁTICA,181.5,BASICO,RUIM
4,1,1,Rede Estadual,1,24,GAVIAO PEIXOTO BRIGADEIRO,5º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,207.9,ADEQUADO,BOM

### Dados da quantidade de classes e alunos

In [4]:
df_classes = pd.read_csv(os.path.join(PATH, 'alunos_classes.csv'), sep=',')
print(df_classes.shape)
df_classes.head()

(4601, 6)

,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,QTD_ALUNOS_ANOS_INICIAIS,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA
0,12,563,16.0,563.0,35.187500,0.750000
1,24,2703,34.0,956.0,28.117647,5.866002
2,36,2164,34.0,1189.0,34.970588,1.193043
3,61,909,30.0,897.0,29.900000,1.953776
4,73,460,17.0,460.0,27.058824,4.115073

### Dados das Escolas (IDESP)

In [5]:
df_idesp = pd.read_csv(os.path.join('../data/raw/', 'IDESP por Escola - 2018.csv'), sep=';')
print(df_idesp.shape)
df_idesp.head()

(5051, 10)

,ANO_LETIVO,CODIGO_CIE,CODIGO_INEP,CODIGO_DIRETORIA,NOME_DIRETORIA,NOME_ESCOLA,NOME_MUNICIPIO,ANOS_INICIAIS,ANOS_FINAIS,ENSINO_MEDIO
0,2018,909075,35909075,10208,LESTE 4,WILFREDO PINHEIRO PROF,SAO PAULO,4.97,2.92,2.45
1,2018,912268,35912268,10207,LESTE 1,IRINEU MONTEIRO DE PINHO REV,SAO PAULO,NaN,2.16,1.37
2,2018,916729,35916729,10104,NORTE 2,GUSTAVO BARROSO,SAO PAULO,NaN,2.74,1.95
3,2018,44283,35044283,10208,LESTE 4,OCTACILIO DE CARVALHO LOPES PROF,SAO PAULO,NaN,NaN,2.74
4,2018,46279,35046279,10208,LESTE 4,ANTONIO SYLVIO DA CUNHA BUENO,SAO PAULO,NaN,2.71,1.41

### Dados das Dependencias

In [6]:
df_dependencias = pd.read_csv(os.path.join(PATH, 'dependencias.csv'), sep=',')
print(df_dependencias.shape)
df_dependencias.head()

(5608, 38)

,CODESC,NOMESC,TIPOESC,TIPOESC_DESC,SITUACAO,SALAS_AULA,SALA_RECURSO,TOT_SALAS_AULA,CANTINA,COPA,REFEITORIO,SALA_LEITURA,TOT_SALA_LEITURA,TOT_QUADRA,SALA_PROF,PATIO_COBERTO,PATIO_DESCOBERTO,TOT_VESTIARIO,LAB_INFO,LAB_CIENCIAS,LAB_CIENCIA_FISICA_BIOLOGICA,TOT_LAB_CIENCIA,LAB_MULTIUSO,OFICINA,DORMITORIO,SANITARIO_ADEQ_DEF,SANITARIO_AL_MASC,SANITARIO_AL_FEM,TOT_SANITARIO_AL,TOT_SANITARIO_FUNC,DEPEND_ADEQ_DEF,SALA_ED_FISICA,SALA_PROG_ESC_FAMILIA,BRINQUEDOTECA,SALA_REFORCO,AREA_SERVICO,SALA_ATENDIMENTO,SALA_ENTRETENIMENTO
0,985429,CEL JTO A EE FLEURIDES CAVALINI MENECHINO PROFA,6,CEL,Ativa,5,0,5,0,0,1,1,1,2,1,1,0,0,1,0,0,0,0,0,0,0,1,1,2,2,1,0,0,0,0,0,0,0
1,31045,DURVALINO GRION PROF,8,EE,Ativa,9,0,9,0,1,0,1,1,1,1,2,0,0,1,0,0,0,0,0,0,1,1,1,2,2,1,0,0,0,0,0,0,0
2,31112,FLEURIDES CAVALLINI MENECHINO PROFA,8,EE,Ativa,12,1,13,0,1,1,1,1,1,1,2,1,2,1,0,0,0,0,0,0,1,2,3,5,2,0,1,0,0,0,0,0,0
3,30806,HELEN KELLER,8,EE,Ativa,16,2,18,1,1,1,1,1,1,1,2,0,0,1,0,0,0,0,0,0,1,2,2,4,2,1,1,1,0,0,0,0,0
4,31264,9 DE JULHO,8,EE,Ativa,21,0,21,0,1,1,1,1,2,1,1,1,2,1,0,0,3,0,0,0,0,1,1,2,2,0,0,1,0,0,0,0,0

### Dados da Formacao dos Servidores

In [7]:
df_formacao_serv = pd.read_csv(os.path.join(PATH, 'formacao_servidores.csv'), sep=',')
print(df_formacao_serv.shape)
df_formacao_serv.head()

(240465, 31)

,REGIAO_EXERC,DE_EXERC,CIE_ESCOLA,UA_EXERC,NOME_UA_EXERC,MUNICIPIO_EXERC,RG12,DI,CPF,NOME,QUADRO_C,CARGO_C,NM_CARGO_C,CATEG_C,DTIEXER_C,QUADRO_E,CARGO_E,NMCARGO_E,CATEG_E,FORMACAO,id_interno,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINOFUNDAMENTAL,FORMACAO_ENSINOMIaDIO,FORMACAO_ESPECIALIZAIaIAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,TITULACAO
0,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,164234.0,1.0,164234.0,164234.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,01/06/2016,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,164234.0,0,0,0,0,0,0,1,0,0,LICENCIATURA
1,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,382145.0,1.0,382145.0,382145.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,08/02/1993,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,LICENCIATURA + BACHARELADO/TECNIOLOGO + ESPECI...,382145.0,0,1,0,0,0,1,1,0,0,ESPECIALIZACAO
2,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,345349.0,1.0,345349.0,345349.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,18/08/1994,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,LICENCIATURA + ESPECIALIZAIaIAO,345349.0,0,0,0,0,0,1,1,0,0,ESPECIALIZACAO
3,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,290900.0,1.0,290900.0,290900.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,03/04/2017,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,290900.0,0,0,0,0,0,0,1,0,0,LICENCIATURA
4,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,316060.0,1.0,316060.0,316060.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,04/06/2018,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,316060.0,0,0,0,0,0,0,1,0,0,LICENCIATURA

### Dados das Coordenadas

In [8]:
df_localizacao = pd.read_csv(os.path.join(PATH, 'localizacao.csv'), sep=',')
print(df_localizacao.shape)
df_localizacao.head()

(1460, 48)

,nomedep,depadm,mun,codmun,de,CD_ESCOLA,CD_DIRETORIA,CD_DIRETORIA_ESTADUAL,CD_DIRETORIA_SUPVS_PROPR,NM_COMPLETO_ESCOLA,CD_UNIDADE,DS_ENDERECO,COMPLEMENTO,NUMERO,CD_ORIGEM_UNIDADE,CD_ORIGEM_ESCOLA,CD_ORIGEM_ENDERECO,LATITUDE,LONGITUDE,DEPADM,DepBol,NomeDepBol,codRMet,CODESC,NOMESC,SERIE_ANO,cod_per,periodo,co_comp,ds_comp,medprof,PONTUACAO,DESEMPENHO,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,Points,CLUSTER
0,ESTADUAL - SE,1,SAO PAULO,100,NORTE 1,36444,10101,10101,10101,GENESIO DE ALMEIDA MOURA DOUTOR,37806,DOMINGOS AREVALO,RUA,862,37806,36444,37866,-23.447000,-46.696700,1,1,Rede Estadual,1,36444,GENESIO DE ALMEIDA MOURA DOUTOR,5º Ano EF,9,GERAL,2,MATEMÁTICA,181.6,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6967 -23.447),14
1,ESTADUAL - SE,1,SAO PAULO,100,LESTE 5,1582,10205,10205,10205,DOMINGOS FAUSTINO SARMIENTO,24902,21 DE ABRIL,RUA,970,24902,1582,24962,-23.542232,-46.605793,1,1,Rede Estadual,1,1582,DOMINGOS FAUSTINO SARMIENTO,5º Ano EF,9,GERAL,2,MATEMÁTICA,218.3,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6057931815944 -23.5422317000605),14
2,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,4388,10316,10316,10316,SEMINARIO NOSSA SENHORA DA GLORIA,37397,RUA MOREIRA DE GODOI,RUA,399,37397,4388,37457,-23.591604,-46.609698,1,1,Rede Estadual,1,4388,SEMINARIO NOSSA SENHORA DA GLORIA,5º Ano EF,9,GERAL,2,MATEMÁTICA,218.7,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6096977 -23.5916041),14
3,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,4424,10316,10316,10316,FRANCISCO DE ASSIS REYS,18610,RUA BOM PASTOR,RUA,1560,18610,4424,18670,-23.590326,-46.607238,1,1,Rede Estadual,1,4424,FRANCISCO DE ASSIS REYS,5º Ano EF,9,GERAL,2,MATEMÁTICA,252.4,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6072382 -23.590326),14
4,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,1739,10316,10316,10316,ANDRE DREYFUS PROFESSOR,12296,RUA PEDRO DE GODOI,RUA,170,12296,1739,12356,-23.587969,-46.582752,1,1,Rede Estadual,1,1739,ANDRE DREYFUS PROFESSOR,5º Ano EF,9,GERAL,2,MATEMÁTICA,227.6,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.5827517 -23.5879693),14

## Criacao de atributos

### Atributos criados atraves da agregacao da Formacao dos Servidores

In [9]:
# ## Selecionando apenas o QUADRO MAGISTERIO
# # df_formacao_serv_QM = df_formacao_serv[df_formacao_serv['QUADRO_C'] == 'QM']
# df_formacao_serv_QM = df_formacao_serv[(df_formacao_serv['QUADRO_C'] == 'QM') & (df_formacao_serv['NM_CARGO_C'] == 'PROFESSOR EDUCACAO BASICA I')]

# qtd_titulacao_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TITULACAO'].value_counts().unstack()
# qtd_titulacao_escola.fillna(0, inplace=True)
# qtd_titulacao_escola.head()

In [10]:
## VERSAO NORMALIZADA

## Selecionando apenas o QUADRO MAGISTERIO e professores da EDUCACAO BASICA I
# df_formacao_serv_QM = df_formacao_serv[df_formacao_serv['QUADRO_C'] == 'QM']
df_formacao_serv_QM = df_formacao_serv[(df_formacao_serv['QUADRO_C'] == 'QM') & (df_formacao_serv['NM_CARGO_C'] == 'PROFESSOR EDUCACAO BASICA I')]

qtd_titulacao_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TITULACAO'].value_counts(normalize=True).unstack()
qtd_titulacao_escola.fillna(0, inplace=True)
qtd_titulacao_escola.head()

TITULACAO,APERF/EXTENSIAOCULTURAL,BACHARELADO/TECNIOLOGO,DOUTORADO,ENSINO_MEDIO,ESPECIALIZACAO,LICENCIATURA,MESTRADO,S/INFO
CIE_ESCOLA,,,,,,,,
0,0.0,0.036053,0.001898,0.037951,0.085389,0.802657,0.036053,0.0
12,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0
24,0.0,0.037037,0.000000,0.074074,0.000000,0.888889,0.000000,0.0
36,0.0,0.250000,0.000000,0.000000,0.250000,0.500000,0.000000,0.0
48,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0

In [11]:
## Qtd de servidores por escola
qtd_servidores = df_formacao_serv_QM.groupby('CIE_ESCOLA').size()
qtd_servidores.name = 'QTD_SERVIDORES'

In [12]:
df_features_formacao = pd.concat([qtd_titulacao_escola, qtd_servidores], axis=1)
df_features_formacao.reset_index(inplace=True)
df_features_formacao.head()

,CIE_ESCOLA,APERF/EXTENSIAOCULTURAL,BACHARELADO/TECNIOLOGO,DOUTORADO,ENSINO_MEDIO,ESPECIALIZACAO,LICENCIATURA,MESTRADO,S/INFO,QTD_SERVIDORES
0,0,0.0,0.036053,0.001898,0.037951,0.085389,0.802657,0.036053,0.0,527
1,12,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,4
2,24,0.0,0.037037,0.000000,0.074074,0.000000,0.888889,0.000000,0.0,27
3,36,0.0,0.250000,0.000000,0.000000,0.250000,0.500000,0.000000,0.0,4
4,48,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,1

## Selecao de atributos e juncao das bases

In [13]:
data = pd.merge(df_localizacao, df_dependencias, left_on='CD_ESCOLA', right_on='CODESC', how='inner')

In [14]:
data = pd.merge(data, df_features_formacao, left_on='CD_ESCOLA', right_on='CIE_ESCOLA', how='inner')

In [15]:
# data = pd.merge(data, df_localizacao[['CD_ESCOLA', 'CLUSTER']], on='CD_ESCOLA', how='inner')

In [16]:
data = pd.merge(data, df_classes, left_on='CD_ESCOLA', right_on='COD_ESC', how='inner')

In [17]:
# data = pd.merge(df_idesp[['CODIGO_CIE', 'ANOS_INICIAIS']], data, left_on='CODIGO_CIE', right_on='CD_ESCOLA', how='inner')

In [18]:
print(data.shape)
data.head()

(1458, 102)

,nomedep,depadm,mun,codmun,de,CD_ESCOLA,CD_DIRETORIA,CD_DIRETORIA_ESTADUAL,CD_DIRETORIA_SUPVS_PROPR,NM_COMPLETO_ESCOLA,CD_UNIDADE,DS_ENDERECO,COMPLEMENTO,NUMERO,CD_ORIGEM_UNIDADE,CD_ORIGEM_ESCOLA,CD_ORIGEM_ENDERECO,LATITUDE,LONGITUDE,DEPADM,DepBol,NomeDepBol,codRMet,CODESC_x,NOMESC_x,SERIE_ANO,cod_per,periodo,co_comp,ds_comp,medprof,PONTUACAO,DESEMPENHO,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,Points,CLUSTER,CODESC_y,NOMESC_y,TIPOESC,TIPOESC_DESC,SITUACAO,SALAS_AULA,SALA_RECURSO,TOT_SALAS_AULA,CANTINA,COPA,REFEITORIO,SALA_LEITURA,TOT_SALA_LEITURA,TOT_QUADRA,SALA_PROF,PATIO_COBERTO,PATIO_DESCOBERTO,TOT_VESTIARIO,LAB_INFO,LAB_CIENCIAS,LAB_CIENCIA_FISICA_BIOLOGICA,TOT_LAB_CIENCIA,LAB_MULTIUSO,OFICINA,DORMITORIO,SANITARIO_ADEQ_DEF,SANITARIO_AL_MASC,SANITARIO_AL_FEM,TOT_SANITARIO_AL,TOT_SANITARIO_FUNC,DEPEND_ADEQ_DEF,SALA_ED_FISICA,SALA_PROG_ESC_FAMILIA,BRINQUEDOTECA,SALA_REFORCO,AREA_SERVICO,SALA_ATENDIMENTO,SALA_ENTRETENIMENTO,CIE_ESCOLA,APERF/EXTENSIAOCULTURAL,BACHARELADO/TECNIOLOGO,DOUTORADO,ENSINO_MEDIO,ESPECIALIZACAO,LICENCIATURA,MESTRADO,S/INFO,QTD_SERVIDORES,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,QTD_ALUNOS_ANOS_INICIAIS,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA
0,ESTADUAL - SE,1,SAO PAULO,100,NORTE 1,36444,10101,10101,10101,GENESIO DE ALMEIDA MOURA DOUTOR,37806,DOMINGOS AREVALO,RUA,862,37806,36444,37866,-23.447000,-46.696700,1,1,Rede Estadual,1,36444,GENESIO DE ALMEIDA MOURA DOUTOR,5º Ano EF,9,GERAL,2,MATEMÁTICA,181.6,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6967 -23.447),14,36444,GENESIO DE ALMEIDA MOURA DOUTOR,8,EE,Ativa,19,0,19,0,0,1,1,1,2,1,0,0,0,1,0,0,0,0,0,0,0,1,1,2,0,0,1,0,0,0,0,0,0,36444,0.0,0.000000,0.0,0.080000,0.040000,0.880000,0.0,0.0,25,36444,1435,36.0,1062.0,29.500000,3.075247
1,ESTADUAL - SE,1,SAO PAULO,100,LESTE 5,1582,10205,10205,10205,DOMINGOS FAUSTINO SARMIENTO,24902,21 DE ABRIL,RUA,970,24902,1582,24962,-23.542232,-46.605793,1,1,Rede Estadual,1,1582,DOMINGOS FAUSTINO SARMIENTO,5º Ano EF,9,GERAL,2,MATEMÁTICA,218.3,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6057931815944 -23.5422317000605),14,1582,DOMINGOS FAUSTINO SARMIENTO,8,EE,Ativa,14,1,15,1,0,2,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,3,3,6,3,0,1,1,0,0,0,0,0,1582,0.0,0.030303,0.0,0.000000,0.090909,0.878788,0.0,0.0,33,1582,822,28.0,818.0,29.214286,1.618347
2,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,4388,10316,10316,10316,SEMINARIO NOSSA SENHORA DA GLORIA,37397,RUA MOREIRA DE GODOI,RUA,399,37397,4388,37457,-23.591604,-46.609698,1,1,Rede Estadual,1,4388,SEMINARIO NOSSA SENHORA DA GLORIA,5º Ano EF,9,GERAL,2,MATEMÁTICA,218.7,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6096977 -23.5916041),14,4388,SEMINARIO NOSSA SENHORA DA GLORIA,8,EE,Ativa,26,0,26,1,0,1,1,1,2,1,2,1,0,1,0,1,1,0,0,0,0,3,3,6,2,0,1,0,0,0,0,0,0,4388,0.0,0.037037,0.0,0.296296,0.037037,0.629630,0.0,0.0,27,4388,1599,48.0,1599.0,33.312500,2.814524
3,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,4424,10316,10316,10316,FRANCISCO DE ASSIS REYS,18610,RUA BOM PASTOR,RUA,1560,18610,4424,18670,-23.590326,-46.607238,1,1,Rede Estadual,1,4424,FRANCISCO DE ASSIS REYS,5º Ano EF,9,GERAL,2,MATEMÁTICA,252.4,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.6072382 -23.590326),14,4424,FRANCISCO DE ASSIS REYS,8,EE,Ativa,11,1,12,1,0,1,1,1,2,1,1,0,0,1,0,0,0,0,0,0,1,1,1,2,0,0,2,0,1,0,0,0,0,4424,0.0,0.031250,0.0,0.093750,0.031250,0.843750,0.0,0.0,32,4424,669,22.0,646.0,29.363636,1.176980
4,ESTADUAL - SE,1,SAO PAULO,100,CENTRO SUL,1739,10316,10316,10316,ANDRE DREYFUS PROFESSOR,12296,RUA PEDRO DE GODOI,RUA,170,12296,1739,12356,-23.587969,-46.582752,1,1,Rede Estadual,1,1739,ANDRE DREYFUS PROFESSOR,5º Ano EF,9,GERAL,2,MATEMÁTICA,227.6,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,POINT (-46.5827517 -23.5879693),14,1739,ANDRE DREYFUS PROFESSOR,8,EE,Ativa,8,1,9,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,2,2,0,1,0,0,0,0,0,0,1739,0.0,0.047619,0.0,0.095238,0.000000,0.857143,0.0,0.0,21,1739,423,16.0,420.0,26.250000,2.489980

In [19]:
data.columns

Index(['nomedep', 'depadm', 'mun', 'codmun', 'de', 'CD_ESCOLA', 'CD_DIRETORIA',
       'CD_DIRETORIA_ESTADUAL', 'CD_DIRETORIA_SUPVS_PROPR',
       'NM_COMPLETO_ESCOLA',
       ...
       'LICENCIATURA', 'MESTRADO', 'S/INFO', 'QTD_SERVIDORES', 'COD_ESC',
       'QTD_TOTAL_ALUNOS', 'QTD_CLASSES', 'QTD_ALUNOS_ANOS_INICIAIS',
       'MEDIA_ALUNOS_SALA', 'STD_ALUNOS_SALA'],
      dtype='object', length=102)

In [20]:
columns_to_remove = [
    'nomedep', 'depadm', 'mun', 'codmun', 'de', 'CD_DIRETORIA',
    'CD_DIRETORIA_ESTADUAL', 'CD_DIRETORIA_SUPVS_PROPR',
    'NM_COMPLETO_ESCOLA', 'CD_UNIDADE', 'DS_ENDERECO', 'COMPLEMENTO',
    'NUMERO', 'CD_ORIGEM_UNIDADE', 'CD_ORIGEM_ESCOLA', 'CD_ORIGEM_ENDERECO',
    'LATITUDE', 'LONGITUDE', 'DEPADM', 'DepBol', 'NomeDepBol', 'codRMet',
    'CODESC_x', 'NOMESC_x', 'SERIE_ANO', 'cod_per', 'periodo', 'co_comp',
    'medprof', 'Points', 'CODESC_y', 'NOMESC_y', 'TIPOESC', 'TIPOESC_DESC', 
    'SITUACAO', 'CIE_ESCOLA', 'CITY'
]

In [21]:
dataset = data.drop(columns_to_remove, axis=1)

In [22]:
print(dataset.shape)
dataset.head()

(1458, 66)

,CD_ESCOLA,ds_comp,PONTUACAO,DESEMPENHO,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,CLUSTER,SALAS_AULA,SALA_RECURSO,TOT_SALAS_AULA,CANTINA,COPA,REFEITORIO,SALA_LEITURA,TOT_SALA_LEITURA,TOT_QUADRA,SALA_PROF,PATIO_COBERTO,PATIO_DESCOBERTO,TOT_VESTIARIO,LAB_INFO,LAB_CIENCIAS,LAB_CIENCIA_FISICA_BIOLOGICA,TOT_LAB_CIENCIA,LAB_MULTIUSO,OFICINA,DORMITORIO,SANITARIO_ADEQ_DEF,SANITARIO_AL_MASC,SANITARIO_AL_FEM,TOT_SANITARIO_AL,TOT_SANITARIO_FUNC,DEPEND_ADEQ_DEF,SALA_ED_FISICA,SALA_PROG_ESC_FAMILIA,BRINQUEDOTECA,SALA_REFORCO,AREA_SERVICO,SALA_ATENDIMENTO,SALA_ENTRETENIMENTO,APERF/EXTENSIAOCULTURAL,BACHARELADO/TECNIOLOGO,DOUTORADO,ENSINO_MEDIO,ESPECIALIZACAO,LICENCIATURA,MESTRADO,S/INFO,QTD_SERVIDORES,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,QTD_ALUNOS_ANOS_INICIAIS,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA
0,36444,MATEMÁTICA,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,14,19,0,19,0,0,1,1,1,2,1,0,0,0,1,0,0,0,0,0,0,0,1,1,2,0,0,1,0,0,0,0,0,0,0.0,0.000000,0.0,0.080000,0.040000,0.880000,0.0,0.0,25,36444,1435,36.0,1062.0,29.500000,3.075247
1,1582,MATEMÁTICA,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,14,14,1,15,1,0,2,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,3,3,6,3,0,1,1,0,0,0,0,0,0.0,0.030303,0.0,0.000000,0.090909,0.878788,0.0,0.0,33,1582,822,28.0,818.0,29.214286,1.618347
2,4388,MATEMÁTICA,BASICO,RUIM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,14,26,0,26,1,0,1,1,1,2,1,2,1,0,1,0,1,1,0,0,0,0,3,3,6,2,0,1,0,0,0,0,0,0,0.0,0.037037,0.0,0.296296,0.037037,0.629630,0.0,0.0,27,4388,1599,48.0,1599.0,33.312500,2.814524
3,4424,MATEMÁTICA,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,14,11,1,12,1,0,1,1,1,2,1,1,0,0,1,0,0,0,0,0,0,1,1,1,2,0,0,2,0,1,0,0,0,0,0.0,0.031250,0.0,0.093750,0.031250,0.843750,0.0,0.0,32,4424,669,22.0,646.0,29.363636,1.176980
4,1739,MATEMÁTICA,ADEQUADO,BOM,SAO PAULO,1.0,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,14,8,1,9,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,2,2,0,1,0,0,0,0,0,0,0.0,0.047619,0.0,0.095238,0.000000,0.857143,0.0,0.0,21,1739,423,16.0,420.0,26.250000,2.489980

## Exportar dataset

In [23]:
dataset.to_csv('../data/processed/dataset.csv', index=False)

In [26]:
data[data['CD_ESCOLA'] == 46541]

,nomedep,depadm,mun,codmun,de,CD_ESCOLA,CD_DIRETORIA,CD_DIRETORIA_ESTADUAL,CD_DIRETORIA_SUPVS_PROPR,NM_COMPLETO_ESCOLA,CD_UNIDADE,DS_ENDERECO,COMPLEMENTO,NUMERO,CD_ORIGEM_UNIDADE,CD_ORIGEM_ESCOLA,CD_ORIGEM_ENDERECO,LATITUDE,LONGITUDE,DEPADM,DepBol,NomeDepBol,codRMet,CODESC_x,NOMESC_x,SERIE_ANO,cod_per,periodo,co_comp,ds_comp,medprof,PONTUACAO,DESEMPENHO,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,Points,CLUSTER,CODESC_y,NOMESC_y,TIPOESC,TIPOESC_DESC,SITUACAO,SALAS_AULA,SALA_RECURSO,TOT_SALAS_AULA,CANTINA,COPA,REFEITORIO,SALA_LEITURA,TOT_SALA_LEITURA,TOT_QUADRA,SALA_PROF,PATIO_COBERTO,PATIO_DESCOBERTO,TOT_VESTIARIO,LAB_INFO,LAB_CIENCIAS,LAB_CIENCIA_FISICA_BIOLOGICA,TOT_LAB_CIENCIA,LAB_MULTIUSO,OFICINA,DORMITORIO,SANITARIO_ADEQ_DEF,SANITARIO_AL_MASC,SANITARIO_AL_FEM,TOT_SANITARIO_AL,TOT_SANITARIO_FUNC,DEPEND_ADEQ_DEF,SALA_ED_FISICA,SALA_PROG_ESC_FAMILIA,BRINQUEDOTECA,SALA_REFORCO,AREA_SERVICO,SALA_ATENDIMENTO,SALA_ENTRETENIMENTO,CIE_ESCOLA,APERF/EXTENSIAOCULTURAL,BACHARELADO/TECNIOLOGO,DOUTORADO,ENSINO_MEDIO,ESPECIALIZACAO,LICENCIATURA,MESTRADO,S/INFO,QTD_SERVIDORES,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,QTD_ALUNOS_ANOS_INICIAIS,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA
1422,ESTADUAL - SE,1,EMBU-GUACU,299,ITAPECERICA DA SERRA,46541,10702,10702,10702,PEDRO VILLAS BOAS DE SOUZA DOM,91243,RUA JOAO RIBEIRO CRAVO ROXO,NaN,SN,91243,46541,125643,-23.8302,-46.814,1,1,Rede Estadual,1,46541,PEDRO VILLAS BOAS DE SOUZA DOM,5º Ano EF,9,GERAL,2,MATEMÁTICA,248.4,ADEQUADO,BOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.81399999999999 -23.8302),8,46541,PEDRO VILLAS BOAS DE SOUZA DOM,8,EE,Ativa,14,0,14,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,2,2,0,0,0,0,0,0,0,0,46541,0.0,0.0,0.0,0.115385,0.038462,0.846154,0.0,0.0,26,46541,649,23.0,649.0,28.217391,1.536126