# Feature Engineering
Criação de features e preparação dos dados para etapa de Machine Learning

#### Imports

In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from unidecode import unidecode

pd.set_option('display.max_columns', None)

## Carregar dados

In [2]:
PATH = '../data/processed/'

### Dados do Desempenho Escolar (SARESP)

In [3]:
# df_escolas = pd.read_csv(os.path.join(PATH, 'escolas_saresp_2018.csv'), sep=',')
# print(df_escolas.shape)
# df_escolas.head()

In [4]:
df_desempenho_escola = pd.read_csv(os.path.join(PATH, 'desempenho_escolas_saresp_2018.csv'), sep=',')
print(df_desempenho_escola.shape)
df_desempenho_escola.head()

(5059, 4)

   CODESC  BOM  RUIM  DESEMPENHO_ESC
0      12  0.0   2.0               0
1      24  1.0   7.0               0
2      36  0.0   4.0               0
3      48  0.0   2.0               0
4      59  0.0   2.0               0

### Dados da quantidade de classes e alunos

In [5]:
df_classes = pd.read_csv(os.path.join(PATH, 'alunos_classes.csv'), sep=',')
print(df_classes.shape)
df_classes.head()

(5596, 11)

,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA,QTD_CLASSES_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_CLASSES_TIPO_ENSINO MEDIO,QTD_CLASSES_TIPO_CEL,QTD_ALUNOS_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_ALUNOS_TIPO_ENSINO MEDIO,QTD_ALUNOS_TIPO_CEL
0,12,563,16,35.187500,0.750000,16.0,0.0,0.0,563.0,0.0,0.0
1,24,2703,88,30.715909,7.214208,34.0,40.0,0.0,956.0,1229.0,0.0
2,36,2164,69,31.362319,8.549116,34.0,29.0,0.0,1189.0,945.0,0.0
3,48,1189,35,33.971429,5.695642,0.0,35.0,0.0,0.0,1189.0,0.0
4,59,974,28,34.785714,5.166539,0.0,28.0,0.0,0.0,974.0,0.0

### Dados das Dependências

In [6]:
df_dependencias = pd.read_csv(os.path.join(PATH, 'dependencias.csv'), sep=',')
print(df_dependencias.shape)
df_dependencias.head()

(5608, 38)

,CODESC,NOMESC,TIPOESC,TIPOESC_DESC,SITUACAO,SALAS_AULA,SALA_RECURSO,TOT_SALAS_AULA,CANTINA,COPA,REFEITORIO,SALA_LEITURA,TOT_SALA_LEITURA,TOT_QUADRA,SALA_PROF,PATIO_COBERTO,PATIO_DESCOBERTO,TOT_VESTIARIO,LAB_INFO,LAB_CIENCIAS,LAB_CIENCIA_FISICA_BIOLOGICA,TOT_LAB_CIENCIA,LAB_MULTIUSO,OFICINA,DORMITORIO,SANITARIO_ADEQ_DEF,SANITARIO_AL_MASC,SANITARIO_AL_FEM,TOT_SANITARIO_AL,TOT_SANITARIO_FUNC,DEPEND_ADEQ_DEF,SALA_ED_FISICA,SALA_PROG_ESC_FAMILIA,BRINQUEDOTECA,SALA_REFORCO,AREA_SERVICO,SALA_ATENDIMENTO,SALA_ENTRETENIMENTO
0,985429,CEL JTO A EE FLEURIDES CAVALINI MENECHINO PROFA,6,CEL,Ativa,5,0,5,0,0,1,1,1,2,1,1,0,0,1,0,0,0,0,0,0,0,1,1,2,2,1,0,0,0,0,0,0,0
1,31045,DURVALINO GRION PROF,8,EE,Ativa,9,0,9,0,1,0,1,1,1,1,2,0,0,1,0,0,0,0,0,0,1,1,1,2,2,1,0,0,0,0,0,0,0
2,31112,FLEURIDES CAVALLINI MENECHINO PROFA,8,EE,Ativa,12,1,13,0,1,1,1,1,1,1,2,1,2,1,0,0,0,0,0,0,1,2,3,5,2,0,1,0,0,0,0,0,0
3,30806,HELEN KELLER,8,EE,Ativa,16,2,18,1,1,1,1,1,1,1,2,0,0,1,0,0,0,0,0,0,1,2,2,4,2,1,1,1,0,0,0,0,0
4,31264,9 DE JULHO,8,EE,Ativa,21,0,21,0,1,1,1,1,2,1,1,1,2,1,0,0,3,0,0,0,0,1,1,2,2,0,0,1,0,0,0,0,0

In [7]:
cols = df_dependencias.tail().columns.drop(['CODESC', 'NOMESC', 'TIPOESC', 'TIPOESC_DESC', 'SITUACAO'])
dict_cols_replace = dict(zip(cols.to_list(), ('DEPENDENCIAS_' + cols).to_list()))
df_dependencias = df_dependencias.rename(columns=dict_cols_replace)

### Dados da Formação dos Servidores

In [8]:
df_formacao_serv = pd.read_csv(os.path.join(PATH, 'formacao_servidores.csv'), sep=',')
print(df_formacao_serv.shape)
df_formacao_serv.head()

(240439, 31)

,REGIAO_EXERC,DE_EXERC,CIE_ESCOLA,UA_EXERC,NOME_UA_EXERC,MUNICIPIO_EXERC,RG12,DI,CPF,NOME,QUADRO_C,CARGO_C,NM_CARGO_C,CATEG_C,DTIEXER_C,QUADRO_E,CARGO_E,NMCARGO_E,CATEG_E,FORMACAO,id_interno,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINOFUNDAMENTAL,FORMACAO_ENSINOMIaDIO,FORMACAO_ESPECIALIZAIaIAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,TITULACAO
0,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,164234.0,1.0,164234.0,164234.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,01/06/2016,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,164234.0,0,0,0,0,0,0,1,0,0,LICENCIATURA
1,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,382145.0,1.0,382145.0,382145.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,08/02/1993,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,LICENCIATURA + BACHARELADO/TECNIOLOGO + ESPECI...,382145.0,0,1,0,0,0,1,1,0,0,ESPECIALIZACAO
2,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,345349.0,1.0,345349.0,345349.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,18/08/1994,QM,6407.0,PROFESSOR EDUCACAO BASICA I,A,LICENCIATURA + ESPECIALIZAIaIAO,345349.0,0,0,0,0,0,1,1,0,0,ESPECIALIZACAO
3,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,290900.0,1.0,290900.0,290900.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,03/04/2017,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,290900.0,0,0,0,0,0,0,1,0,0,LICENCIATURA
4,INTERIOR,D.E.REG. RIBEIRAO PRETO,911306,79305,EE ROSANGELA BASILE-PROFA.,RIBEIRAO PRETO,316060.0,1.0,316060.0,316060.0,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,04/06/2018,QM,6407.0,PROFESSOR EDUCACAO BASICA I,O,LICENCIATURA,316060.0,0,0,0,0,0,0,1,0,0,LICENCIATURA

### Dados da jornada dos servidores

In [9]:
df_jornada = pd.read_csv(os.path.join(PATH, 'jornada.csv'), sep=',')
print(df_jornada.shape)
df_jornada.head()

(5369, 16)

,CODESC,JORNADA_QTD_DISCIPLINAS_mean,JORNADA_QTD_DISCIPLINAS_std,JORNADA_QTD_DISCIPLINAS_max,JORNADA_QTD_TOTAL_AULAS_mean,JORNADA_QTD_TOTAL_AULAS_std,JORNADA_QTD_TOTAL_AULAS_max,SERVIDORES_IDADE_mean,SERVIDORES_IDADE_std,SERVIDORES_TEMPO_CARGO_C_mean,SERVIDORES_TEMPO_CARGO_C_std,SERVIDORES_CAT_FUNCIONAL_A,SERVIDORES_CAT_FUNCIONAL_F,SERVIDORES_CAT_FUNCIONAL_N,SERVIDORES_CAT_FUNCIONAL_O,SERVIDORES_CAT_FUNCIONAL_P
0,24,3.486726,1.768348,10,48.849558,20.847756,108,47.024096,8.739224,10.819277,6.428119,0.789157,0.144578,0.0,0.066265,0.0
1,36,2.975000,1.492386,8,46.525000,19.308931,104,45.460784,8.618541,8.598039,5.794952,0.754902,0.176471,0.0,0.068627,0.0
2,48,2.125000,0.489246,4,44.375000,16.629409,64,45.744681,8.709081,9.361702,7.330671,0.851064,0.106383,0.0,0.042553,0.0
3,59,2.150000,0.533494,4,42.500000,16.195916,98,42.972973,8.337032,7.810811,6.094407,0.783784,0.135135,0.0,0.081081,0.0
4,61,2.488889,0.869227,4,48.755556,8.668531,64,47.955556,7.210964,11.400000,10.242893,0.600000,0.155556,0.0,0.244444,0.0

### Dados das Coordenadas

In [10]:
df_localizacao = pd.read_csv(os.path.join(PATH, 'localizacao.csv'), sep=',')
print(df_localizacao.shape)
df_localizacao.head()

(5051, 25)

,mun,codmun,de,CD_ESCOLA,CD_UNIDADE,DS_ENDERECO,COMPLEMENTO,NUMERO,LATITUDE,LONGITUDE,CODESC,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,CLUSTER
0,SAO PAULO,100,NORTE 1,36444,37806,DOMINGOS AREVALO,RUA,862,-23.447000,-46.696700,36444,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2
1,SAO PAULO,100,LESTE 5,1582,24902,21 DE ABRIL,RUA,970,-23.542232,-46.605793,1582,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2
2,SAO PAULO,100,LESTE 5,2173,24901,ITAPURA,RUA,976,-23.547300,-46.566000,2173,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,15
3,SAO PAULO,100,LESTE 1,3086,24918,VIRGINIA DE MIRANDA,RUA,138,-23.526587,-46.452888,3086,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,15
4,SAO PAULO,100,LESTE 1,2884,24923,RUA SAO BERTOLDO,RUA,449,-23.494297,-46.457064,2884,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,15

### Dados do historico dos gestores

In [11]:
df_gestores = pd.read_csv('../data/processed/gestores_historico.csv')
print(df_gestores.shape)
df_gestores.head()

(4706, 16)

,CD_ESCOLA,DIRETORES_QTD_2018,VICE_DIRETOR_QTD_2018,COORDENADORES_QTD_2018,DIRETORES_QTD_5_ANOS,VICE_DIRETOR_QTD_5_ANOS,COORDENADORES_QTD_5_ANOS,DIRETOR_CPF,DIRETOR_CIE_ESCOLA,DIRETOR_CARGO_E,DIRETOR_NOMECAR_E,DIRETOR_IDADE,DIRETOR_CARGO_CLAS_EXER_IGUAIS,DIRETOR_ANOS_TRAB_CARGO_C,DIRETOR_ANOS_TRAB_CARGO_C.1,DIRETOR_ANOS_TRAB_CARGO_E
0,24,3.0,6.0,3.0,11.0,19.0,17.0,140419.0,24,6200.0,DIRETOR DE ESCOLA,33.0,1,0.0,0.0,0.0
1,36,4.0,5.0,3.0,13.0,15.0,13.0,361644.0,36,6200.0,DIRETOR DE ESCOLA,50.0,0,18.0,18.0,0.0
2,48,2.0,1.0,2.0,8.0,12.0,10.0,334774.0,48,6200.0,DIRETOR DE ESCOLA,58.0,0,18.0,18.0,2.0
3,59,4.0,2.0,1.0,12.0,7.0,6.0,149926.0,59,6200.0,DIRETOR DE ESCOLA,38.0,0,10.0,10.0,0.0
4,61,2.0,2.0,2.0,10.0,5.0,8.0,342266.0,61,6200.0,DIRETOR DE ESCOLA,53.0,1,9.0,9.0,9.0

### Dados Avaliação Nacional de Alfabetização (ANA) (dados externos)

In [12]:
df_ana = pd.read_csv(os.path.join('../data/external/', 'TS_Municipio_2016.xlsx - Plan1.csv'), sep=',')
print(df_ana.shape)

(29571, 18)

In [13]:
leitura_cols = list(filter(lambda x: True if 'LEITURA' in x else False, df_ana.columns))
escrita_cols = list(filter(lambda x: True if 'ESCRITA' in x else False, df_ana.columns))
matematica_cols = list(filter(lambda x: True if 'MATEMÁTICA' in x else False, df_ana.columns))

In [14]:
### Filtrar apenas dados do estado de SP
df_ana = df_ana[df_ana['UF'] == 35]

In [15]:
df_ana[df_ana['CÓDIGO DO MUNICÍPIO'] == 3513504]

,UF,CÓDIGO DO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,LOCALIZACAO,LEITURA_Nível 1,LEITURA_Nível 2,LEITURA_Nível 3,LEITURA_Nível 4,ESCRITA_Nível 1,ESCRITA_Nível 2,ESCRITA_Nível 3,ESCRITA_Nível 4,ESCRITA_Nível 5,MATEMÁTICA_Nível 1,MATEMÁTICA_Nível 2,MATEMÁTICA_Nível 3,MATEMÁTICA_Nível 4
18301,35,3513504,Cubatão,Estadual,Todos,13.85,29.75,38.92,17.49,9.83,11.28,0.57,64.18,14.14,12.6,29.58,18.85,38.96
18302,35,3513504,Cubatão,Estadual,Urbana,13.85,29.75,38.92,17.49,9.83,11.28,0.57,64.18,14.14,12.6,29.58,18.85,38.96

In [16]:
df_ana.loc[18301, 'REDE'] = 'Todos'

In [17]:
df_ana = df_ana[(df_ana['LOCALIZACAO'] == 'Todos') & (df_ana['REDE'] == 'Todos')]

In [18]:
df_ana['MATEMATICA'] = df_ana[matematica_cols].apply(lambda x: x.argmax(), axis=1) + 1
df_ana['LEITURA'] = df_ana[leitura_cols].apply(lambda x: x.argmax(), axis=1) + 1
df_ana['ESCRITA'] = df_ana[escrita_cols].apply(lambda x: x.argmax(), axis=1) + 1

## Criação de atributos

### Atributos criados através da agregação da Formação dos Servidores

In [19]:
# df_formacao_serv.drop_duplicates(subset=['CPF'], keep='last')

In [20]:
# ## Selecionando apenas o QUADRO MAGISTERIO
# # df_formacao_serv_QM = df_formacao_serv[df_formacao_serv['QUADRO_C'] == 'QM']
# df_formacao_serv_QM = df_formacao_serv[(df_formacao_serv['QUADRO_C'] == 'QM') & (df_formacao_serv['NM_CARGO_C'] == 'PROFESSOR EDUCACAO BASICA I')]

# qtd_titulacao_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TITULACAO'].value_counts().unstack()
# qtd_titulacao_escola.fillna(0, inplace=True)
# qtd_titulacao_escola.head()

In [21]:
formacao_cols = list(filter(lambda x: True if 'FORMACAO_' in x else False, df_formacao_serv.columns))

In [22]:
# df_formacao_serv[(df_formacao_serv['QUADRO_C'] == 'QM') & (df_formacao_serv['NM_CARGO_C'].str.contains('PROFESSOR', na=False))].shape
# df_formacao_serv.head(2)

In [23]:
## VERSAO NORMALIZADA

## Selecionando apenas o QUADRO MAGISTERIO
df_formacao_serv_QM = df_formacao_serv[df_formacao_serv['QUADRO_E'] == 'QM']

## Selecionando apenas o QUADRO MAGISTERIO e professores da EDUCACAO BASICA I
# df_formacao_serv_QM = df_formacao_serv[(df_formacao_serv['QUADRO_C'] == 'QM') & (df_formacao_serv['NM_CARGO_C'] == 'PROFESSOR EDUCACAO BASICA I')]

# 
df_formacao_serv_QM = df_formacao_serv[(df_formacao_serv['QUADRO_E'] == 'QM') & (df_formacao_serv['NMCARGO_E'].str.contains('PROFESSOR', na=False))]

qtd_titulacao_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TITULACAO'].value_counts(normalize=True).unstack()
# qtd_titulacao_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TITULACAO'].value_counts().unstack()
qtd_titulacao_escola.fillna(0, inplace=True)
qtd_titulacao_escola.columns = 'FORMACAO_' + qtd_titulacao_escola.columns
qtd_titulacao_escola.head()

TITULACAO,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINO_MEDIO,FORMACAO_ESPECIALIZACAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO
CIE_ESCOLA,,,,,,,,
0,0.0,0.055755,0.010072,0.006835,0.093165,0.748921,0.085252,0.0
12,0.0,0.000000,0.000000,0.000000,0.034483,0.896552,0.068966,0.0
24,0.0,0.101695,0.008475,0.016949,0.016949,0.771186,0.084746,0.0
36,0.0,0.095238,0.011905,0.000000,0.142857,0.738095,0.011905,0.0
48,0.0,0.090909,0.018182,0.000000,0.018182,0.836364,0.036364,0.0

In [24]:
qtd_formacao = df_formacao_serv_QM[formacao_cols].sum(axis=1)
df_formacao_serv_QM.loc[qtd_formacao.index, 'QTD_FORMACAO'] = qtd_formacao

/home/milton/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/milton/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [25]:
media_titulos_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['QTD_FORMACAO'].mean()
media_titulos_escola.name = 'MEDIA_FORMACOES'

In [26]:
formacao_continuada_cols = ['FORMACAO_DOUTORADO', 'FORMACAO_ESPECIALIZAIaIAO', 'FORMACAO_MESTRADO']

In [27]:
df_formacao_serv_QM['TEM_FORMACAO_CONTINUADA'] = df_formacao_serv_QM[formacao_continuada_cols].any(axis=1).astype(int)

/home/milton/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [28]:
qtd_titulacao_continuada_escola = df_formacao_serv_QM.groupby('CIE_ESCOLA')['TEM_FORMACAO_CONTINUADA'].sum()
qtd_titulacao_continuada_escola.name = 'QTD_FORMACAO_CONTINUADA'

In [29]:
## Qtd de professores por escola
qtd_professores = df_formacao_serv_QM.groupby('CIE_ESCOLA').size()
qtd_professores.name = 'QTD_PROFESSORES'

In [30]:
## Qtd de servidores por escola
qtd_servidores = df_formacao_serv.groupby('CIE_ESCOLA').size()
qtd_servidores.name = 'QTD_SERVIDORES'

In [31]:
qtd_cargos_distintos = df_formacao_serv.groupby('CIE_ESCOLA')['NMCARGO_E'].nunique()
qtd_cargos_distintos.name = 'QTD_CARGOS_DISTINTOS'

In [32]:
df_features_formacao = pd.concat([qtd_titulacao_escola, qtd_servidores, qtd_professores, media_titulos_escola, qtd_titulacao_continuada_escola, qtd_cargos_distintos], axis=1)
df_features_formacao.dropna(inplace=True)
df_features_formacao.reset_index(inplace=True)
df_features_formacao.head()

,CIE_ESCOLA,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINO_MEDIO,FORMACAO_ESPECIALIZACAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,QTD_SERVIDORES,QTD_PROFESSORES,MEDIA_FORMACOES,QTD_FORMACAO_CONTINUADA,QTD_CARGOS_DISTINTOS
0,0,0.0,0.055755,0.010072,0.006835,0.093165,0.748921,0.085252,0.0,8571,2780,1.276978,524,41
1,12,0.0,0.000000,0.000000,0.000000,0.034483,0.896552,0.068966,0.0,37,29,1.103448,3,3
2,24,0.0,0.101695,0.008475,0.016949,0.016949,0.771186,0.084746,0.0,139,118,1.228814,13,6
3,36,0.0,0.095238,0.011905,0.000000,0.142857,0.738095,0.011905,0.0,92,84,1.297619,14,4
4,48,0.0,0.090909,0.018182,0.000000,0.018182,0.836364,0.036364,0.0,66,55,1.163636,4,5

### Obter formacao dos diretores

In [33]:
df_gestores = pd.merge(df_gestores, df_formacao_serv[['CPF', 'CIE_ESCOLA', 'TITULACAO']].drop_duplicates(['CPF', 'CIE_ESCOLA']), left_on=['DIRETOR_CPF', 'DIRETOR_CIE_ESCOLA'], right_on=['CPF', 'CIE_ESCOLA'], how='inner')

In [34]:
df_gestores = df_gestores.rename(columns={'TITULACAO': 'DIRETOR_TITULACAO'})
df_gestores.drop(['DIRETOR_CIE_ESCOLA', 'DIRETOR_CPF', 'DIRETOR_CARGO_E', 'DIRETOR_NOMECAR_E', 'DIRETOR_CIE_ESCOLA', 'CIE_ESCOLA', 'CPF'], axis=1, inplace=True)

### Jornada

In [35]:
df_jornada_features = df_jornada.groupby('CODESC').agg(['mean', 'std', 'max'])
df_jornada_features.columns = ['JORNADA_' + c[0] + '_' + c[1] for c in df_jornada_features.columns]
df_jornada_features.reset_index(inplace=True)
df_jornada_features.fillna(0, inplace=True)
df_jornada_features.head()

,CODESC,JORNADA_JORNADA_QTD_DISCIPLINAS_mean_mean,JORNADA_JORNADA_QTD_DISCIPLINAS_mean_std,JORNADA_JORNADA_QTD_DISCIPLINAS_mean_max,JORNADA_JORNADA_QTD_DISCIPLINAS_std_mean,JORNADA_JORNADA_QTD_DISCIPLINAS_std_std,JORNADA_JORNADA_QTD_DISCIPLINAS_std_max,JORNADA_JORNADA_QTD_DISCIPLINAS_max_mean,JORNADA_JORNADA_QTD_DISCIPLINAS_max_std,JORNADA_JORNADA_QTD_DISCIPLINAS_max_max,JORNADA_JORNADA_QTD_TOTAL_AULAS_mean_mean,JORNADA_JORNADA_QTD_TOTAL_AULAS_mean_std,JORNADA_JORNADA_QTD_TOTAL_AULAS_mean_max,JORNADA_JORNADA_QTD_TOTAL_AULAS_std_mean,JORNADA_JORNADA_QTD_TOTAL_AULAS_std_std,JORNADA_JORNADA_QTD_TOTAL_AULAS_std_max,JORNADA_JORNADA_QTD_TOTAL_AULAS_max_mean,JORNADA_JORNADA_QTD_TOTAL_AULAS_max_std,JORNADA_JORNADA_QTD_TOTAL_AULAS_max_max,JORNADA_SERVIDORES_IDADE_mean_mean,JORNADA_SERVIDORES_IDADE_mean_std,JORNADA_SERVIDORES_IDADE_mean_max,JORNADA_SERVIDORES_IDADE_std_mean,JORNADA_SERVIDORES_IDADE_std_std,JORNADA_SERVIDORES_IDADE_std_max,JORNADA_SERVIDORES_TEMPO_CARGO_C_mean_mean,JORNADA_SERVIDORES_TEMPO_CARGO_C_mean_std,JORNADA_SERVIDORES_TEMPO_CARGO_C_mean_max,JORNADA_SERVIDORES_TEMPO_CARGO_C_std_mean,JORNADA_SERVIDORES_TEMPO_CARGO_C_std_std,JORNADA_SERVIDORES_TEMPO_CARGO_C_std_max,JORNADA_SERVIDORES_CAT_FUNCIONAL_A_mean,JORNADA_SERVIDORES_CAT_FUNCIONAL_A_std,JORNADA_SERVIDORES_CAT_FUNCIONAL_A_max,JORNADA_SERVIDORES_CAT_FUNCIONAL_F_mean,JORNADA_SERVIDORES_CAT_FUNCIONAL_F_std,JORNADA_SERVIDORES_CAT_FUNCIONAL_F_max,JORNADA_SERVIDORES_CAT_FUNCIONAL_N_mean,JORNADA_SERVIDORES_CAT_FUNCIONAL_N_std,JORNADA_SERVIDORES_CAT_FUNCIONAL_N_max,JORNADA_SERVIDORES_CAT_FUNCIONAL_O_mean,JORNADA_SERVIDORES_CAT_FUNCIONAL_O_std,JORNADA_SERVIDORES_CAT_FUNCIONAL_O_max,JORNADA_SERVIDORES_CAT_FUNCIONAL_P_mean,JORNADA_SERVIDORES_CAT_FUNCIONAL_P_std,JORNADA_SERVIDORES_CAT_FUNCIONAL_P_max
0,24,3.486726,0.0,3.486726,1.768348,0.0,1.768348,10,0.0,10,48.849558,0.0,48.849558,20.847756,0.0,20.847756,108,0.0,108,47.024096,0.0,47.024096,8.739224,0.0,8.739224,10.819277,0.0,10.819277,6.428119,0.0,6.428119,0.789157,0.0,0.789157,0.144578,0.0,0.144578,0.0,0.0,0.0,0.066265,0.0,0.066265,0.0,0.0,0.0
1,36,2.975000,0.0,2.975000,1.492386,0.0,1.492386,8,0.0,8,46.525000,0.0,46.525000,19.308931,0.0,19.308931,104,0.0,104,45.460784,0.0,45.460784,8.618541,0.0,8.618541,8.598039,0.0,8.598039,5.794952,0.0,5.794952,0.754902,0.0,0.754902,0.176471,0.0,0.176471,0.0,0.0,0.0,0.068627,0.0,0.068627,0.0,0.0,0.0
2,48,2.125000,0.0,2.125000,0.489246,0.0,0.489246,4,0.0,4,44.375000,0.0,44.375000,16.629409,0.0,16.629409,64,0.0,64,45.744681,0.0,45.744681,8.709081,0.0,8.709081,9.361702,0.0,9.361702,7.330671,0.0,7.330671,0.851064,0.0,0.851064,0.106383,0.0,0.106383,0.0,0.0,0.0,0.042553,0.0,0.042553,0.0,0.0,0.0
3,59,2.150000,0.0,2.150000,0.533494,0.0,0.533494,4,0.0,4,42.500000,0.0,42.500000,16.195916,0.0,16.195916,98,0.0,98,42.972973,0.0,42.972973,8.337032,0.0,8.337032,7.810811,0.0,7.810811,6.094407,0.0,6.094407,0.783784,0.0,0.783784,0.135135,0.0,0.135135,0.0,0.0,0.0,0.081081,0.0,0.081081,0.0,0.0,0.0
4,61,2.488889,0.0,2.488889,0.869227,0.0,0.869227,4,0.0,4,48.755556,0.0,48.755556,8.668531,0.0,8.668531,64,0.0,64,47.955556,0.0,47.955556,7.210964,0.0,7.210964,11.400000,0.0,11.400000,10.242893,0.0,10.242893,0.600000,0.0,0.600000,0.155556,0.0,0.155556,0.0,0.0,0.0,0.244444,0.0,0.244444,0.0,0.0,0.0

## Manipulação dos dados de ANA

### Juntar código do município

#### Formatar texto e corrigir municípios com erros no nome

In [36]:
df_ana['NOME DO MUNICÍPIO'] = df_ana['NOME DO MUNICÍPIO'].apply(lambda x: unidecode(x.upper().replace('-', ' ')))

In [37]:
df_localizacao['mun'] = df_localizacao['mun'].str.replace('FLORINEA', 'FLORINIA')

In [38]:
df_ana['NOME DO MUNICÍPIO'] = df_ana['NOME DO MUNICÍPIO'].str.replace('SAO LUIS DO PARAITINGA', 'SAO LUIZ DO PARAITINGA')
df_ana['NOME DO MUNICÍPIO'] = df_ana['NOME DO MUNICÍPIO'].str.replace('MOJI MIRIM', 'MOGI MIRIM')

#### Juntar das bases de dados

In [39]:
df_ana_localizacao = pd.merge(df_localizacao[['mun', 'codmun', 'de', 'CD_ESCOLA']], df_ana, left_on='mun', right_on='NOME DO MUNICÍPIO', how='left')
df_ana_localizacao.shape

(5051, 25)

#### Preenchimento dos dados faltantes
Para os dois casos que o munícipio da escola não foi localizado na base externa, realizar a junção com o *DE*.

In [40]:
df_ana_loc_null = df_ana_localizacao[df_ana_localizacao['NOME DO MUNICÍPIO'].isnull()]
df_ana_loc_null

,mun,codmun,de,CD_ESCOLA,UF,CÓDIGO DO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,LOCALIZACAO,LEITURA_Nível 1,LEITURA_Nível 2,LEITURA_Nível 3,LEITURA_Nível 4,ESCRITA_Nível 1,ESCRITA_Nível 2,ESCRITA_Nível 3,ESCRITA_Nível 4,ESCRITA_Nível 5,MATEMÁTICA_Nível 1,MATEMÁTICA_Nível 2,MATEMÁTICA_Nível 3,MATEMÁTICA_Nível 4,MATEMATICA,LEITURA,ESCRITA
1687,ANALANDIA,169,PIRASSUNUNGA,21301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3296,PARISI,759,VOTUPORANGA,29221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df_complemento = pd.merge(df_ana_loc_null.reset_index()[['index','mun', 'codmun', 'de', 'CD_ESCOLA']], df_ana, left_on='de', right_on='NOME DO MUNICÍPIO', how='left')
df_complemento.set_index('index', inplace=True)
df_complemento

,mun,codmun,de,CD_ESCOLA,UF,CÓDIGO DO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,LOCALIZACAO,LEITURA_Nível 1,LEITURA_Nível 2,LEITURA_Nível 3,LEITURA_Nível 4,ESCRITA_Nível 1,ESCRITA_Nível 2,ESCRITA_Nível 3,ESCRITA_Nível 4,ESCRITA_Nível 5,MATEMÁTICA_Nível 1,MATEMÁTICA_Nível 2,MATEMÁTICA_Nível 3,MATEMÁTICA_Nível 4,MATEMATICA,LEITURA,ESCRITA
index,,,,,,,,,,,,,,,,,,,,,,,,,
1687,ANALANDIA,169,PIRASSUNUNGA,21301,35,3539301,PIRASSUNUNGA,Todos,Todos,15.19,34.01,34.93,15.88,8.03,13.79,1.55,68.01,8.62,18.64,29.20,19.74,32.41,4,3,4
3296,PARISI,759,VOTUPORANGA,29221,35,3557105,VOTUPORANGA,Todos,Todos,7.36,28.78,44.15,19.71,3.88,4.64,0.58,71.62,19.27,11.16,24.75,23.15,40.95,4,3,4

In [42]:
df_ana_localizacao.loc[df_complemento.index] = df_complemento
df_ana_localizacao.loc[df_complemento.index]

,mun,codmun,de,CD_ESCOLA,UF,CÓDIGO DO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,LOCALIZACAO,LEITURA_Nível 1,LEITURA_Nível 2,LEITURA_Nível 3,LEITURA_Nível 4,ESCRITA_Nível 1,ESCRITA_Nível 2,ESCRITA_Nível 3,ESCRITA_Nível 4,ESCRITA_Nível 5,MATEMÁTICA_Nível 1,MATEMÁTICA_Nível 2,MATEMÁTICA_Nível 3,MATEMÁTICA_Nível 4,MATEMATICA,LEITURA,ESCRITA
index,,,,,,,,,,,,,,,,,,,,,,,,,
1687,ANALANDIA,169,PIRASSUNUNGA,21301,35.0,3539301.0,PIRASSUNUNGA,Todos,Todos,15.19,34.01,34.93,15.88,8.03,13.79,1.55,68.01,8.62,18.64,29.20,19.74,32.41,4.0,3.0,4.0
3296,PARISI,759,VOTUPORANGA,29221,35.0,3557105.0,VOTUPORANGA,Todos,Todos,7.36,28.78,44.15,19.71,3.88,4.64,0.58,71.62,19.27,11.16,24.75,23.15,40.95,4.0,3.0,4.0

## Junção das bases

In [43]:
df_desempenho_escola.reset_index(inplace=True, drop=True)

In [44]:
df_localizacao = df_localizacao.drop_duplicates(subset=['CD_ESCOLA'])

In [45]:
data = pd.merge(df_desempenho_escola, df_localizacao, on='CODESC', how='inner')

In [46]:
data = pd.merge(data, df_dependencias, on='CODESC', how='inner')

In [47]:
data = pd.merge(data, df_features_formacao, left_on='CD_ESCOLA', right_on='CIE_ESCOLA', how='inner')

In [48]:
data = pd.merge(data, df_classes, left_on='CD_ESCOLA', right_on='COD_ESC', how='inner')

In [49]:
data = pd.merge(data, df_gestores, on='CD_ESCOLA', how='inner')

In [50]:
print(data.shape)
data = pd.merge(data, df_jornada, on='CODESC', how='inner')
print(data.shape)

(4695, 102)
(4523, 117)

In [51]:
data = pd.merge(data, df_ana_localizacao[['CD_ESCOLA', 'MATEMATICA', 'LEITURA', 'ESCRITA']].drop_duplicates(subset=['CD_ESCOLA']), on='CD_ESCOLA', how='left')

In [52]:
# data = pd.merge(df_idesp[['CODIGO_CIE', 'ANOS_INICIAIS']], data, left_on='CODIGO_CIE', right_on='CD_ESCOLA', how='inner')

In [53]:
print(data.shape)
data.head()

(4523, 120)

,CODESC,BOM,RUIM,DESEMPENHO_ESC,mun,codmun,de,CD_ESCOLA,CD_UNIDADE,DS_ENDERECO,COMPLEMENTO,NUMERO,LATITUDE,LONGITUDE,CITY,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,CLUSTER,NOMESC,TIPOESC,TIPOESC_DESC,SITUACAO,DEPENDENCIAS_SALAS_AULA,DEPENDENCIAS_SALA_RECURSO,DEPENDENCIAS_TOT_SALAS_AULA,DEPENDENCIAS_CANTINA,DEPENDENCIAS_COPA,DEPENDENCIAS_REFEITORIO,DEPENDENCIAS_SALA_LEITURA,DEPENDENCIAS_TOT_SALA_LEITURA,DEPENDENCIAS_TOT_QUADRA,DEPENDENCIAS_SALA_PROF,DEPENDENCIAS_PATIO_COBERTO,DEPENDENCIAS_PATIO_DESCOBERTO,DEPENDENCIAS_TOT_VESTIARIO,DEPENDENCIAS_LAB_INFO,DEPENDENCIAS_LAB_CIENCIAS,DEPENDENCIAS_LAB_CIENCIA_FISICA_BIOLOGICA,DEPENDENCIAS_TOT_LAB_CIENCIA,DEPENDENCIAS_LAB_MULTIUSO,DEPENDENCIAS_OFICINA,DEPENDENCIAS_DORMITORIO,DEPENDENCIAS_SANITARIO_ADEQ_DEF,DEPENDENCIAS_SANITARIO_AL_MASC,DEPENDENCIAS_SANITARIO_AL_FEM,DEPENDENCIAS_TOT_SANITARIO_AL,DEPENDENCIAS_TOT_SANITARIO_FUNC,DEPENDENCIAS_DEPEND_ADEQ_DEF,DEPENDENCIAS_SALA_ED_FISICA,DEPENDENCIAS_SALA_PROG_ESC_FAMILIA,DEPENDENCIAS_BRINQUEDOTECA,DEPENDENCIAS_SALA_REFORCO,DEPENDENCIAS_AREA_SERVICO,DEPENDENCIAS_SALA_ATENDIMENTO,DEPENDENCIAS_SALA_ENTRETENIMENTO,CIE_ESCOLA,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINO_MEDIO,FORMACAO_ESPECIALIZACAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,QTD_SERVIDORES,QTD_PROFESSORES,MEDIA_FORMACOES,QTD_FORMACAO_CONTINUADA,QTD_CARGOS_DISTINTOS,COD_ESC,QTD_TOTAL_ALUNOS,QTD_CLASSES,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA,QTD_CLASSES_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_CLASSES_TIPO_ENSINO MEDIO,QTD_CLASSES_TIPO_CEL,QTD_ALUNOS_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_ALUNOS_TIPO_ENSINO MEDIO,QTD_ALUNOS_TIPO_CEL,DIRETORES_QTD_2018,VICE_DIRETOR_QTD_2018,COORDENADORES_QTD_2018,DIRETORES_QTD_5_ANOS,VICE_DIRETOR_QTD_5_ANOS,COORDENADORES_QTD_5_ANOS,DIRETOR_IDADE,DIRETOR_CARGO_CLAS_EXER_IGUAIS,DIRETOR_ANOS_TRAB_CARGO_C,DIRETOR_ANOS_TRAB_CARGO_C.1,DIRETOR_ANOS_TRAB_CARGO_E,DIRETOR_TITULACAO,JORNADA_QTD_DISCIPLINAS_mean,JORNADA_QTD_DISCIPLINAS_std,JORNADA_QTD_DISCIPLINAS_max,JORNADA_QTD_TOTAL_AULAS_mean,JORNADA_QTD_TOTAL_AULAS_std,JORNADA_QTD_TOTAL_AULAS_max,SERVIDORES_IDADE_mean,SERVIDORES_IDADE_std,SERVIDORES_TEMPO_CARGO_C_mean,SERVIDORES_TEMPO_CARGO_C_std,SERVIDORES_CAT_FUNCIONAL_A,SERVIDORES_CAT_FUNCIONAL_F,SERVIDORES_CAT_FUNCIONAL_N,SERVIDORES_CAT_FUNCIONAL_O,SERVIDORES_CAT_FUNCIONAL_P,MATEMATICA,LEITURA,ESCRITA
0,24,1.0,7.0,0,SAO PAULO,100,NORTE 1,24,31204,MOGEIRO,RUA,710,-23.404700,-46.759400,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,GAVIAO PEIXOTO BRIGADEIRO,8,EE,Ativa,35,0,35,1,0,1,1,1,2,1,1,1,0,2,0,1,1,0,0,0,0,1,1,2,2,1,1,0,0,0,0,0,0,24,0.0,0.101695,0.008475,0.016949,0.016949,0.771186,0.084746,0.0,139,118,1.228814,13,6,24,2703,88,30.715909,7.214208,34.0,40.0,0.0,956.0,1229.0,0.0,3.0,6.0,3.0,11.0,19.0,17.0,33.0,1,0.0,0.0,0.0,ESPECIALIZACAO,3.486726,1.768348,10,48.849558,20.847756,108,47.024096,8.739224,10.819277,6.428119,0.789157,0.144578,0.0,0.066265,0.0,4.0,3.0,4.0
1,36,0.0,4.0,0,SAO PAULO,100,NORTE 1,36,37353,DO SABAO,ESTRADA,1497,-23.481279,-46.700821,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,JOAO SOLIMEO,8,EE,Ativa,21,1,22,1,0,3,1,1,2,1,1,0,0,2,0,1,1,3,0,0,0,1,1,2,2,0,1,0,0,1,0,0,0,36,0.0,0.095238,0.011905,0.000000,0.142857,0.738095,0.011905,0.0,92,84,1.297619,14,4,36,2164,69,31.362319,8.549116,34.0,29.0,0.0,1189.0,945.0,0.0,4.0,5.0,3.0,13.0,15.0,13.0,50.0,0,18.0,18.0,0.0,ESPECIALIZACAO,2.975000,1.492386,8,46.525000,19.308931,104,45.460784,8.618541,8.598039,5.794952,0.754902,0.176471,0.0,0.068627,0.0,4.0,3.0,4.0
2,48,0.0,2.0,0,SAO PAULO,100,NORTE 1,48,1,DEPUTADO CANTIDIO SAMPAIO,NaN,1701,-23.462601,-46.681400,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,WALFREDO ARANTES CALDAS PROFESSOR,8,EE,Ativa,19,0,19,1,0,0,1,1,1,1,1,0,0,2,0,2,2,1,0,0,0,3,3,6,3,0,0,0,0,0,0,0,0,48,0.0,0.090909,0.018182,0.000000,0.018182,0.836364,0.036364,0.0,66,55,1.163636,4,5,48,1189,35,33.971429,5.695642,0.0,35.0,0.0,0.0,1189.0,0.0,2.0,1.0,2.0,8.0,12.0,10.0,58.0,0,18.0,18.0,2.0,LICENCIATURA,2.125000,0.489246,4,44.375000,16.629409,64,45.744681,8.709081,9.361702,7.330671,0.851064,0.106383,0.0,0.042553,0.0,4.0,3.0,4.0
3,59,0.0,2.0,0,SAO PAULO,100,NORTE 1,59,37354,RUA FRANCISCO GIRON,ESTRADA,SN,-23.437950,-46.792249,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,SEBASTIAO DE OLIVEIRA GUSMAO PROFESSOR,8,EE,Ativa,11,0,11,0,0,0,1,1,1,1,0,2,0,1,0,0,1,0,0,0,0,1,2,3,3,0,1,0,0,0,0,0,0,59,0.0,0.093023,0.000000,0.000000,0.023256,0.813953,0.069767,0.0,49,43,1.209302,4,4,59,974,28,34.785714,5.166539,0.0,28.0,0.0,0.0,974.0,0.0,4.0,2.0,1.0,12.0,7.0,6.0,38.0,0,10.0,10.0,0.0,LICENCIATURA,2.150000,0.533494,4,42.500000,16.195916,98,42.972973,8.337032,7.810811,6.094407,0.783784,0.135135,0.0,0.081081,0.0,4.0,3.0,4.0
4,61,3.0,1.0,1,SAO PAULO,100,NORTE 1,61,2,ANTONIO MAIA,RUA,691,-23.406830,-46.755070,SAO PAULO,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,SUZANA DE CAMPOS DONA,8,EE,Ativa,15,1,16,0,1,1,1,1,1,1,1,0,2,1,0,0,0,0,0,0,0,1,1,2,5,0,0,0,0,0,0,0,0,61,0.0,0.039216,0.000000,0.098039,0.039216,0.803922,0.019608,0.0,59,51,1.078431,3,4,61,909,33,27.545455,7.814613,30.0,0.0,0.0,897.0,0.0,0.0,2.0,2.0,2.0,10.0,5.0,8.0,53.0,1,9.0,9.0,9.0,LICENCIATURA,2.488889,0.869227,4,48.755556,8.668531,64,47.955556,7.210964,11.400000,10.242893,0.600000,0.155556,0.0,0.244444,0.0,4.0,3.0,4.0

### Criação de atributo para computar a quantidade de alunos por servidor
QTD ALUNOS ÷ QTD SERVIDORES

In [54]:
data['RELACAO_ALUNO_POR_SERVIDOR'] = data['QTD_TOTAL_ALUNOS'] / data['QTD_SERVIDORES']
data['RELACAO_ALUNO_POR_PROFESSOR'] = data['QTD_TOTAL_ALUNOS'] / data['QTD_PROFESSORES']

### Seleção de atributos

In [55]:
columns_to_remove = [
    'mun', 'codmun', 'de', 'DS_ENDERECO', 'COMPLEMENTO', 'NOMESC', 'TIPOESC', 'TIPOESC_DESC', 'SITUACAO',
    'NUMERO', 'LATITUDE', 'LONGITUDE', 'CIE_ESCOLA', 'CITY', 'CODESC', 'COD_ESC', 'CD_UNIDADE'
]

In [56]:
dataset = data.drop(columns_to_remove, axis=1)

In [57]:
print(dataset.shape)
dataset.head()

(4523, 105)

,BOM,RUIM,DESEMPENHO_ESC,CD_ESCOLA,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,CLUSTER,DEPENDENCIAS_SALAS_AULA,DEPENDENCIAS_SALA_RECURSO,DEPENDENCIAS_TOT_SALAS_AULA,DEPENDENCIAS_CANTINA,DEPENDENCIAS_COPA,DEPENDENCIAS_REFEITORIO,DEPENDENCIAS_SALA_LEITURA,DEPENDENCIAS_TOT_SALA_LEITURA,DEPENDENCIAS_TOT_QUADRA,DEPENDENCIAS_SALA_PROF,DEPENDENCIAS_PATIO_COBERTO,DEPENDENCIAS_PATIO_DESCOBERTO,DEPENDENCIAS_TOT_VESTIARIO,DEPENDENCIAS_LAB_INFO,DEPENDENCIAS_LAB_CIENCIAS,DEPENDENCIAS_LAB_CIENCIA_FISICA_BIOLOGICA,DEPENDENCIAS_TOT_LAB_CIENCIA,DEPENDENCIAS_LAB_MULTIUSO,DEPENDENCIAS_OFICINA,DEPENDENCIAS_DORMITORIO,DEPENDENCIAS_SANITARIO_ADEQ_DEF,DEPENDENCIAS_SANITARIO_AL_MASC,DEPENDENCIAS_SANITARIO_AL_FEM,DEPENDENCIAS_TOT_SANITARIO_AL,DEPENDENCIAS_TOT_SANITARIO_FUNC,DEPENDENCIAS_DEPEND_ADEQ_DEF,DEPENDENCIAS_SALA_ED_FISICA,DEPENDENCIAS_SALA_PROG_ESC_FAMILIA,DEPENDENCIAS_BRINQUEDOTECA,DEPENDENCIAS_SALA_REFORCO,DEPENDENCIAS_AREA_SERVICO,DEPENDENCIAS_SALA_ATENDIMENTO,DEPENDENCIAS_SALA_ENTRETENIMENTO,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINO_MEDIO,FORMACAO_ESPECIALIZACAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,QTD_SERVIDORES,QTD_PROFESSORES,MEDIA_FORMACOES,QTD_FORMACAO_CONTINUADA,QTD_CARGOS_DISTINTOS,QTD_TOTAL_ALUNOS,QTD_CLASSES,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA,QTD_CLASSES_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_CLASSES_TIPO_ENSINO MEDIO,QTD_CLASSES_TIPO_CEL,QTD_ALUNOS_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_ALUNOS_TIPO_ENSINO MEDIO,QTD_ALUNOS_TIPO_CEL,DIRETORES_QTD_2018,VICE_DIRETOR_QTD_2018,COORDENADORES_QTD_2018,DIRETORES_QTD_5_ANOS,VICE_DIRETOR_QTD_5_ANOS,COORDENADORES_QTD_5_ANOS,DIRETOR_IDADE,DIRETOR_CARGO_CLAS_EXER_IGUAIS,DIRETOR_ANOS_TRAB_CARGO_C,DIRETOR_ANOS_TRAB_CARGO_C.1,DIRETOR_ANOS_TRAB_CARGO_E,DIRETOR_TITULACAO,JORNADA_QTD_DISCIPLINAS_mean,JORNADA_QTD_DISCIPLINAS_std,JORNADA_QTD_DISCIPLINAS_max,JORNADA_QTD_TOTAL_AULAS_mean,JORNADA_QTD_TOTAL_AULAS_std,JORNADA_QTD_TOTAL_AULAS_max,SERVIDORES_IDADE_mean,SERVIDORES_IDADE_std,SERVIDORES_TEMPO_CARGO_C_mean,SERVIDORES_TEMPO_CARGO_C_std,SERVIDORES_CAT_FUNCIONAL_A,SERVIDORES_CAT_FUNCIONAL_F,SERVIDORES_CAT_FUNCIONAL_N,SERVIDORES_CAT_FUNCIONAL_O,SERVIDORES_CAT_FUNCIONAL_P,MATEMATICA,LEITURA,ESCRITA,RELACAO_ALUNO_POR_SERVIDOR,RELACAO_ALUNO_POR_PROFESSOR
0,1.0,7.0,0,24,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,35,0,35,1,0,1,1,1,2,1,1,1,0,2,0,1,1,0,0,0,0,1,1,2,2,1,1,0,0,0,0,0,0,0.0,0.101695,0.008475,0.016949,0.016949,0.771186,0.084746,0.0,139,118,1.228814,13,6,2703,88,30.715909,7.214208,34.0,40.0,0.0,956.0,1229.0,0.0,3.0,6.0,3.0,11.0,19.0,17.0,33.0,1,0.0,0.0,0.0,ESPECIALIZACAO,3.486726,1.768348,10,48.849558,20.847756,108,47.024096,8.739224,10.819277,6.428119,0.789157,0.144578,0.0,0.066265,0.0,4.0,3.0,4.0,19.446043,22.906780
1,0.0,4.0,0,36,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,21,1,22,1,0,3,1,1,2,1,1,0,0,2,0,1,1,3,0,0,0,1,1,2,2,0,1,0,0,1,0,0,0,0.0,0.095238,0.011905,0.000000,0.142857,0.738095,0.011905,0.0,92,84,1.297619,14,4,2164,69,31.362319,8.549116,34.0,29.0,0.0,1189.0,945.0,0.0,4.0,5.0,3.0,13.0,15.0,13.0,50.0,0,18.0,18.0,0.0,ESPECIALIZACAO,2.975000,1.492386,8,46.525000,19.308931,104,45.460784,8.618541,8.598039,5.794952,0.754902,0.176471,0.0,0.068627,0.0,4.0,3.0,4.0,23.521739,25.761905
2,0.0,2.0,0,48,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,19,0,19,1,0,0,1,1,1,1,1,0,0,2,0,2,2,1,0,0,0,3,3,6,3,0,0,0,0,0,0,0,0,0.0,0.090909,0.018182,0.000000,0.018182,0.836364,0.036364,0.0,66,55,1.163636,4,5,1189,35,33.971429,5.695642,0.0,35.0,0.0,0.0,1189.0,0.0,2.0,1.0,2.0,8.0,12.0,10.0,58.0,0,18.0,18.0,2.0,LICENCIATURA,2.125000,0.489246,4,44.375000,16.629409,64,45.744681,8.709081,9.361702,7.330671,0.851064,0.106383,0.0,0.042553,0.0,4.0,3.0,4.0,18.015152,21.618182
3,0.0,2.0,0,59,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,11,0,11,0,0,0,1,1,1,1,0,2,0,1,0,0,1,0,0,0,0,1,2,3,3,0,1,0,0,0,0,0,0,0.0,0.093023,0.000000,0.000000,0.023256,0.813953,0.069767,0.0,49,43,1.209302,4,4,974,28,34.785714,5.166539,0.0,28.0,0.0,0.0,974.0,0.0,4.0,2.0,1.0,12.0,7.0,6.0,38.0,0,10.0,10.0,0.0,LICENCIATURA,2.150000,0.533494,4,42.500000,16.195916,98,42.972973,8.337032,7.810811,6.094407,0.783784,0.135135,0.0,0.081081,0.0,4.0,3.0,4.0,19.877551,22.651163
4,3.0,1.0,1,61,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,15,1,16,0,1,1,1,1,1,1,1,0,2,1,0,0,0,0,0,0,0,1,1,2,5,0,0,0,0,0,0,0,0,0.0,0.039216,0.000000,0.098039,0.039216,0.803922,0.019608,0.0,59,51,1.078431,3,4,909,33,27.545455,7.814613,30.0,0.0,0.0,897.0,0.0,0.0,2.0,2.0,2.0,10.0,5.0,8.0,53.0,1,9.0,9.0,9.0,LICENCIATURA,2.488889,0.869227,4,48.755556,8.668531,64,47.955556,7.210964,11.400000,10.242893,0.600000,0.155556,0.0,0.244444,0.0,4.0,3.0,4.0,15.406780,17.823529

## Exportar base de dados

In [58]:
dataset.head()

,BOM,RUIM,DESEMPENHO_ESC,CD_ESCOLA,CAPITAL,AREA,ESTIMATED_POP,RURAL_URBAN,GVA_PUBLIC,GVA_TOTAL,GDP,GDP_CAPITA,COMP_H,COMP_O,COMP_P,COMP_Q,CLUSTER,DEPENDENCIAS_SALAS_AULA,DEPENDENCIAS_SALA_RECURSO,DEPENDENCIAS_TOT_SALAS_AULA,DEPENDENCIAS_CANTINA,DEPENDENCIAS_COPA,DEPENDENCIAS_REFEITORIO,DEPENDENCIAS_SALA_LEITURA,DEPENDENCIAS_TOT_SALA_LEITURA,DEPENDENCIAS_TOT_QUADRA,DEPENDENCIAS_SALA_PROF,DEPENDENCIAS_PATIO_COBERTO,DEPENDENCIAS_PATIO_DESCOBERTO,DEPENDENCIAS_TOT_VESTIARIO,DEPENDENCIAS_LAB_INFO,DEPENDENCIAS_LAB_CIENCIAS,DEPENDENCIAS_LAB_CIENCIA_FISICA_BIOLOGICA,DEPENDENCIAS_TOT_LAB_CIENCIA,DEPENDENCIAS_LAB_MULTIUSO,DEPENDENCIAS_OFICINA,DEPENDENCIAS_DORMITORIO,DEPENDENCIAS_SANITARIO_ADEQ_DEF,DEPENDENCIAS_SANITARIO_AL_MASC,DEPENDENCIAS_SANITARIO_AL_FEM,DEPENDENCIAS_TOT_SANITARIO_AL,DEPENDENCIAS_TOT_SANITARIO_FUNC,DEPENDENCIAS_DEPEND_ADEQ_DEF,DEPENDENCIAS_SALA_ED_FISICA,DEPENDENCIAS_SALA_PROG_ESC_FAMILIA,DEPENDENCIAS_BRINQUEDOTECA,DEPENDENCIAS_SALA_REFORCO,DEPENDENCIAS_AREA_SERVICO,DEPENDENCIAS_SALA_ATENDIMENTO,DEPENDENCIAS_SALA_ENTRETENIMENTO,FORMACAO_APERF/EXTENSIAOCULTURAL,FORMACAO_BACHARELADO/TECNIOLOGO,FORMACAO_DOUTORADO,FORMACAO_ENSINO_MEDIO,FORMACAO_ESPECIALIZACAO,FORMACAO_LICENCIATURA,FORMACAO_MESTRADO,FORMACAO_S/INFO,QTD_SERVIDORES,QTD_PROFESSORES,MEDIA_FORMACOES,QTD_FORMACAO_CONTINUADA,QTD_CARGOS_DISTINTOS,QTD_TOTAL_ALUNOS,QTD_CLASSES,MEDIA_ALUNOS_SALA,STD_ALUNOS_SALA,QTD_CLASSES_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_CLASSES_TIPO_ENSINO MEDIO,QTD_CLASSES_TIPO_CEL,QTD_ALUNOS_TIPO_ENSINO FUNDAMENTAL DE 9 ANOS,QTD_ALUNOS_TIPO_ENSINO MEDIO,QTD_ALUNOS_TIPO_CEL,DIRETORES_QTD_2018,VICE_DIRETOR_QTD_2018,COORDENADORES_QTD_2018,DIRETORES_QTD_5_ANOS,VICE_DIRETOR_QTD_5_ANOS,COORDENADORES_QTD_5_ANOS,DIRETOR_IDADE,DIRETOR_CARGO_CLAS_EXER_IGUAIS,DIRETOR_ANOS_TRAB_CARGO_C,DIRETOR_ANOS_TRAB_CARGO_C.1,DIRETOR_ANOS_TRAB_CARGO_E,DIRETOR_TITULACAO,JORNADA_QTD_DISCIPLINAS_mean,JORNADA_QTD_DISCIPLINAS_std,JORNADA_QTD_DISCIPLINAS_max,JORNADA_QTD_TOTAL_AULAS_mean,JORNADA_QTD_TOTAL_AULAS_std,JORNADA_QTD_TOTAL_AULAS_max,SERVIDORES_IDADE_mean,SERVIDORES_IDADE_std,SERVIDORES_TEMPO_CARGO_C_mean,SERVIDORES_TEMPO_CARGO_C_std,SERVIDORES_CAT_FUNCIONAL_A,SERVIDORES_CAT_FUNCIONAL_F,SERVIDORES_CAT_FUNCIONAL_N,SERVIDORES_CAT_FUNCIONAL_O,SERVIDORES_CAT_FUNCIONAL_P,MATEMATICA,LEITURA,ESCRITA,RELACAO_ALUNO_POR_SERVIDOR,RELACAO_ALUNO_POR_PROFESSOR
0,1.0,7.0,0,24,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,35,0,35,1,0,1,1,1,2,1,1,1,0,2,0,1,1,0,0,0,0,1,1,2,2,1,1,0,0,0,0,0,0,0.0,0.101695,0.008475,0.016949,0.016949,0.771186,0.084746,0.0,139,118,1.228814,13,6,2703,88,30.715909,7.214208,34.0,40.0,0.0,956.0,1229.0,0.0,3.0,6.0,3.0,11.0,19.0,17.0,33.0,1,0.0,0.0,0.0,ESPECIALIZACAO,3.486726,1.768348,10,48.849558,20.847756,108,47.024096,8.739224,10.819277,6.428119,0.789157,0.144578,0.0,0.066265,0.0,4.0,3.0,4.0,19.446043,22.906780
1,0.0,4.0,0,36,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,21,1,22,1,0,3,1,1,2,1,1,0,0,2,0,1,1,3,0,0,0,1,1,2,2,0,1,0,0,1,0,0,0,0.0,0.095238,0.011905,0.000000,0.142857,0.738095,0.011905,0.0,92,84,1.297619,14,4,2164,69,31.362319,8.549116,34.0,29.0,0.0,1189.0,945.0,0.0,4.0,5.0,3.0,13.0,15.0,13.0,50.0,0,18.0,18.0,0.0,ESPECIALIZACAO,2.975000,1.492386,8,46.525000,19.308931,104,45.460784,8.618541,8.598039,5.794952,0.754902,0.176471,0.0,0.068627,0.0,4.0,3.0,4.0,23.521739,25.761905
2,0.0,2.0,0,48,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,19,0,19,1,0,0,1,1,1,1,1,0,0,2,0,2,2,1,0,0,0,3,3,6,3,0,0,0,0,0,0,0,0,0.0,0.090909,0.018182,0.000000,0.018182,0.836364,0.036364,0.0,66,55,1.163636,4,5,1189,35,33.971429,5.695642,0.0,35.0,0.0,0.0,1189.0,0.0,2.0,1.0,2.0,8.0,12.0,10.0,58.0,0,18.0,18.0,2.0,LICENCIATURA,2.125000,0.489246,4,44.375000,16.629409,64,45.744681,8.709081,9.361702,7.330671,0.851064,0.106383,0.0,0.042553,0.0,4.0,3.0,4.0,18.015152,21.618182
3,0.0,2.0,0,59,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,11,0,11,0,0,0,1,1,1,1,0,2,0,1,0,0,1,0,0,0,0,1,2,3,3,0,1,0,0,0,0,0,0,0.0,0.093023,0.000000,0.000000,0.023256,0.813953,0.069767,0.0,49,43,1.209302,4,4,974,28,34.785714,5.166539,0.0,28.0,0.0,0.0,974.0,0.0,4.0,2.0,1.0,12.0,7.0,6.0,38.0,0,10.0,10.0,0.0,LICENCIATURA,2.150000,0.533494,4,42.500000,16.195916,98,42.972973,8.337032,7.810811,6.094407,0.783784,0.135135,0.0,0.081081,0.0,4.0,3.0,4.0,19.877551,22.651163
4,3.0,1.0,1,61,1,1521.11,12176866.0,Urbano,41902892.72,5.699105e+08,6.870359e+08,57071.43,19515.0,153.0,16030.0,22248.0,2,15,1,16,0,1,1,1,1,1,1,1,0,2,1,0,0,0,0,0,0,0,1,1,2,5,0,0,0,0,0,0,0,0,0.0,0.039216,0.000000,0.098039,0.039216,0.803922,0.019608,0.0,59,51,1.078431,3,4,909,33,27.545455,7.814613,30.0,0.0,0.0,897.0,0.0,0.0,2.0,2.0,2.0,10.0,5.0,8.0,53.0,1,9.0,9.0,9.0,LICENCIATURA,2.488889,0.869227,4,48.755556,8.668531,64,47.955556,7.210964,11.400000,10.242893,0.600000,0.155556,0.0,0.244444,0.0,4.0,3.0,4.0,15.406780,17.823529

In [59]:
dataset.to_csv('../data/processed/dataset.csv', index=False)